layout:
  application:
    - name: facade
      source: asset:clientFacade
      target: "{{ joinFilePath .Target .ClientPackage }}"
      file_name: "{{ .Name }}_client.go"
    - name: utils
      source: "templates/utils.gtpl"
      target: "{{ joinFilePath .Target }}/resources/utils"
      file_name: "helper_functions.go"
  models:
    - name: definition
      source: asset:model
      target: "{{ joinFilePath .Target .ModelPackage }}"
      file_name: "{{ (snakize (pascalize .Name)) }}.go"
    - name: schema
      source: "templates/schema.gtpl"
      target: "{{ joinFilePath .Target }}/schema"
      file_name: "{{ camelize .Name }}_schema.go"
    - name: datadump
      source: "templates/datadump.gtpl"
      target: "{{ joinFilePath .Target }}/data_profile"
      file_name: "{{ camelize .Name }}_models.profile"
  operations:
    - name: parameters
      source: asset:clientParameter
      target: "{{ joinFilePath .Target .ClientPackage .Package }}"
      file_name: "{{ (snakize (pascalize .Name)) }}_parameters.go"
    - name: responses
      source: asset:clientResponse
      target: "{{ joinFilePath .Target .ClientPackage .Package }}"
      file_name: "{{ (snakize (pascalize .Name)) }}_responses.go"
  operation_groups:
    - name: client
      source: asset:clientClient
      target: "{{ joinFilePath .Target .ClientPackage .Name }}"
      file_name: "{{ (snakize (pascalize .Name)) }}_client.go"
    - name: resources
      source: "templates/resources.gtpl"
      target: "{{ joinFilePath .Target }}/resources"
      file_name: "{{ camelize .Name }}_resource.go"
    - name: datadump
      source: "templates/datadump.gtpl"
      target: "{{ joinFilePath .Target }}/resource_profile"
      file_name: "{{ camelize .Name }}_resource.profile"
